# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    tags:
      - v*.*.* 
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run Maven package
      run: mvn package
    - name: Upload acceptance jar
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: acceptance-artifacts
        path: /**/**/Asset_Tracker-acceptance*.jar
    - name: Run docker build
      run: docker build -t mcawte/asset-tracker:latest .
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push to Docker Hub
      run: docker push mcawte/asset-tracker:latest

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Does console out
      run: ls -ahl /github/workspace


